version: "3.4"

services:
  build:
    image: yio-remote/build
    container_name: yio-remote-build
    hostname: yio-builder
    volumes:
      - ./build-output:/yio-remote/target
      - source:/yio-remote/src
      - buildroot:/yio-remote/buildroot
      # note: multiple mounts in the same root dir don't show up with df -h! Use cat /proc/mounts to verify
    command: build

volumes:
  source:
    name: yio-projects
  buildroot:
    name: yio-buildroot
