#!/bin/bash
#
# Wrapper build script for yio-remote/build Docker image
# https://github.com/YIO-Remote/documentation/wiki
# Copy this script to /usr/local/bin to call it from anywhere
#
# Uses environment variable $YIO_BUILD_OUTPUT
# Either define it in your shell environment (e.g. ~/.bash_profile or ~/.profile)
# or define it in your current session: export YIO_BUILD_OUTPUT=/projects/yio/build-output
#

set -e

#YIO_BUILD_OUTPUT=/projects/yio/build-output 

# --- Helper functions ---

function checkDockerVolume() {
    docker volume inspect $1 &> /dev/null || {
        echo "Docker volume '$1' doesn't exist: creating it..."
        docker volume create $1
    }
}

# --- Script starts here ---

if [[ -z "${YIO_BUILD_OUTPUT}" ]]; then
    echo "Environment variable YIO_BUILD_OUTPUT not defined!"
    exit 1
fi

if [ ! -d ${YIO_BUILD_OUTPUT} ]; then
    echo "Output directory defined in 'YIO_BUILD_OUTPUT' doesn't exist: '${YIO_BUILD_OUTPUT}'"
    exit 1
fi

which docker &> /dev/null || {
    echo "Docker not found in path"
    exit 1
}

docker version &> /dev/null || {
    echo "Docker is not running"
    exit 1
}

checkDockerVolume yio-projects
checkDockerVolume yio-buildroot

docker run --rm -it \
    -v yio-projects:/yio-remote/src \
    -v yio-buildroot:/yio-remote/buildroot \
    -v ${YIO_BUILD_OUTPUT}:/yio-remote/target \
    gcr.io/yio-remote/build $@
